# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-04 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0011_auto_20210204_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='barth_rooms',
            new_name='bath_rooms',
        ),
    ]
